version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - milogert
  assignees:
  - milogert
  ignore:
  - dependency-name: importlib-metadata
    versions:
    - 3.10.0
    - 3.10.1
    - 3.4.0
    - 3.6.0
    - 3.7.0
    - 3.7.2
    - 3.7.3
    - 3.9.0
    - 4.0.0
  - dependency-name: pygments
    versions:
    - 2.7.4
    - 2.8.0
  - dependency-name: more-itertools
    versions:
    - 8.6.0
  - dependency-name: zipp
    versions:
    - 3.4.0
