version: '3'
services:
  bggrss:
    build: .
    image: bggrss_app
    command: flask run --host=0.0.0.0
    environment:
      - TZ=America/Chicago
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
