name: Test and Deploy

on:
  push:	
    branches:	
      - master

jobs:
  testDeploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@master
    - name: Get python
      uses: actions/setup-python@v1
    - name: Get pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install env
      run: pipenv install
    - name: Test
      run: pipenv run pytest
    - name: Deploy
      uses: maddox/actions/ssh@master
      env:
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
      with:
        args: "cd bggrss && git pull && sudo systemctl restart bggrss.service"
