name: Test everything

on: [push, pull_request]
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@master
    - name: Get python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Get pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install env
      run: pipenv install
    - name: Test
      run: pipenv run pytest
